version: 2
updates:
- package-ecosystem: "bundler"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "composer"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "elm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "mix"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "nuget"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "pub"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
- package-ecosystem: "terraform"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: Asia/Tokyo
